import React, { useState, useEffect } from 'react'
import {
  CCard,
  CCardBody,
  CCardHeader,
  CCol,
  CRow,
  CTable,
  CTableBody,
  CTableDataCell,
  CTableHead,
  CTableHeaderCell,
  CTableRow,
  CButton,
  CModal,
  CModalHeader,
  CModalTitle,
  CModalBody,
  CModalFooter,
  CForm,
  CFormInput,
  CFormLabel,
  CFormTextarea,
  CFormCheck,
  CSpinner,
  CAlert,
  CBadge,
} from '@coreui/react'
import CIcon from '@coreui/icons-react'
import {
  cilPlus,
  cilPencil,
  cilTrash,
  cilCheckCircle,
  cilXCircle,
} from '@coreui/icons'
import { masterApi } from '../../../api/reservationApi'

const Items = () => {
  const [items, setItems] = useState([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  
  const [showModal, setShowModal] = useState(false)
  const [modalMode, setModalMode] = useState('add')
  const [currentItem, setCurrentItem] = useState(null)
  
  // Delete confirmation modal state
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [deleteItemId, setDeleteItemId] = useState(null)
  const [deleteItemName, setDeleteItemName] = useState('')
  
  const [formData, setFormData] = useState({
    name: '',
    code: '',
    description: '',
    isActive: true,
  })

  useEffect(() => {
    loadItems()
  }, [])

  const loadItems = async () => {
    setLoading(true)
    try {
      const response = await masterApi.getItems()
      const itemsData = Array.isArray(response.data.data) ? response.data.data : []
      // Sort items by code in ascending order
      const sortedItems = itemsData.sort((a, b) => {
        const codeA = parseInt(a.code) || 0
        const codeB = parseInt(b.code) || 0
        return codeA - codeB
      })
      setItems(sortedItems)
    } catch (err) {
      setError('Failed to load items')
      console.error('Error loading items:', err)
    } finally {
      setLoading(false)
    }
  }

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }))
  }

  const handleAdd = () => {
    setModalMode('add')
    setFormData({
      name: '',
      code: '', // Will be auto-generated by backend
      description: '',
      isActive: true,
    })
    setCurrentItem(null)
    setShowModal(true)
    setError('')
    setSuccess('')
  }

  const handleEdit = (item) => {
    setModalMode('edit')
    setFormData({
      name: item.name,
      code: item.code,
      description: item.description || '',
      isActive: item.isActive,
    })
    setCurrentItem(item)
    setShowModal(true)
    setError('')
    setSuccess('')
  }

  const handleSave = async () => {
    if (!formData.name) {
      setError('Name is required')
      return
    }

    setLoading(true)
    setError('')
    setSuccess('')

    try {
      if (modalMode === 'add') {
        const response = await masterApi.createItem(formData)
        console.log('Item creation response:', response.data) // Debug log
        const createdItem = response.data?.data
        const generatedCode = createdItem?.code
        
        console.log('Generated code:', generatedCode) // Debug log
        
        if (generatedCode) {
          // Update form data immediately to show the generated code in the form
          setFormData(prev => {
            const updated = { ...prev, code: generatedCode }
            console.log('Updated formData:', updated) // Debug log
            return updated
          })
          setSuccess(`Item created successfully! Generated Code: ${generatedCode}`)
          
          // Keep modal open for 4 seconds to show the generated code, then close
          setTimeout(async () => {
            await loadItems()
            setShowModal(false)
          // Reset form after closing
          setFormData({
            name: '',
            code: '',
            description: '',
            isActive: true,
          })
          }, 4000)
        } else {
          setSuccess('Item created successfully!')
          await loadItems()
          setShowModal(false)
        }
        setTimeout(() => setSuccess(''), 5000)
      } else {
        await masterApi.updateItem(currentItem.id, formData)
        setSuccess('Item updated successfully!')
        await loadItems()
        setShowModal(false)
        setTimeout(() => setSuccess(''), 3000)
      }
    } catch (err) {
      console.error('Error creating item:', err) // Debug log
      setError(err.response?.data?.message || 'Failed to save item')
    } finally {
      setLoading(false)
    }
  }

  const handleDeleteClick = (item) => {
    setDeleteItemId(item.id)
    setDeleteItemName(item.name)
    setShowDeleteModal(true)
  }

  const handleDelete = async () => {
    setShowDeleteModal(false)
    setLoading(true)
    setError('')
    setSuccess('')

    try {
      await masterApi.deleteItem(deleteItemId)
      setSuccess('Item deleted successfully!')
      await loadItems()
      setTimeout(() => setSuccess(''), 3000)
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to delete item')
    } finally {
      setLoading(false)
      setDeleteItemId(null)
      setDeleteItemName('')
    }
  }

  const handleCancelDelete = () => {
    setShowDeleteModal(false)
    setDeleteItemId(null)
    setDeleteItemName('')
  }

  return (
    <CRow>
      <CCol xs={12}>
        <CCard className="mb-4">
          <CCardHeader className="d-flex justify-content-between align-items-center">
            <strong>Items Management</strong>
            <CButton color="primary" size="sm" onClick={handleAdd}>
              <CIcon icon={cilPlus} className="me-2" />
              Add Item
            </CButton>
          </CCardHeader>
          <CCardBody>
            {error && (
              <CAlert color="danger" dismissible onClose={() => setError('')}>
                {error}
              </CAlert>
            )}
            {success && (
              <CAlert color="success" dismissible onClose={() => setSuccess('')}>
                {success}
              </CAlert>
            )}

            {loading && !showModal && (
              <div className="text-center py-4">
                <CSpinner color="primary" />
                <div className="mt-2">Loading...</div>
              </div>
            )}

            {!loading && (
              <CTable hover responsive>
                <CTableHead>
                  <CTableRow>
                    <CTableHeaderCell scope="col">#</CTableHeaderCell>
                    <CTableHeaderCell scope="col">Name</CTableHeaderCell>
                    <CTableHeaderCell scope="col">Code</CTableHeaderCell>
                    <CTableHeaderCell scope="col">Description</CTableHeaderCell>
                    <CTableHeaderCell scope="col">Status</CTableHeaderCell>
                    <CTableHeaderCell scope="col">Actions</CTableHeaderCell>
                  </CTableRow>
                </CTableHead>
                <CTableBody>
                  {items.length === 0 ? (
                    <CTableRow>
                      <CTableDataCell colSpan={6} className="text-center">
                        No items found. Click "Add Item" to create one.
                      </CTableDataCell>
                    </CTableRow>
                  ) : (
                    items.map((item, index) => (
                      <CTableRow key={item.id}>
                        <CTableHeaderCell scope="row">{index + 1}</CTableHeaderCell>
                        <CTableDataCell>{item.name}</CTableDataCell>
                        <CTableDataCell>
                          <code>{item.code}</code>
                        </CTableDataCell>
                        <CTableDataCell>{item.description || '-'}</CTableDataCell>
                        <CTableDataCell>
                          {item.isActive ? (
                            <CBadge color="success">
                              <CIcon icon={cilCheckCircle} className="me-1" size="sm" />
                              Active
                            </CBadge>
                          ) : (
                            <CBadge color="secondary">
                              <CIcon icon={cilXCircle} className="me-1" size="sm" />
                              Inactive
                            </CBadge>
                          )}
                        </CTableDataCell>
                        <CTableDataCell>
                          <CButton
                            color="info"
                            size="sm"
                            className="me-2"
                            onClick={() => handleEdit(item)}
                          >
                            <CIcon icon={cilPencil} size="sm" />
                          </CButton>
                          <CButton
                            color="danger"
                            size="sm"
                            onClick={() => handleDeleteClick(item)}
                          >
                            <CIcon icon={cilTrash} size="sm" />
                          </CButton>
                        </CTableDataCell>
                      </CTableRow>
                    ))
                  )}
                </CTableBody>
              </CTable>
            )}
          </CCardBody>
        </CCard>
      </CCol>

      <CModal visible={showModal} onClose={() => setShowModal(false)} size="lg">
        <CModalHeader>
          <CModalTitle>
            {modalMode === 'add' ? 'Add New Item' : 'Edit Item'}
          </CModalTitle>
        </CModalHeader>
        <CModalBody>
          <CForm>
            <CRow className="mb-3">
              <CCol md={6}>
                <CFormLabel htmlFor="name">
                  Item Name <span className="text-danger">*</span>
                </CFormLabel>
                <CFormInput
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  placeholder="Enter item name"
                  required
                />
              </CCol>
              <CCol md={6}>
                <CFormLabel htmlFor="code">
                  Code {modalMode === 'add' && '(Auto-generated)'}
                </CFormLabel>
                <CFormInput
                  type="text"
                  id="code"
                  name="code"
                  value={formData.code || ''}
                  onChange={handleChange}
                  placeholder={modalMode === 'add' && !formData.code ? 'Auto-generated numerical code' : ''}
                  readOnly={modalMode === 'add'}
                  disabled={false}
                  className={formData.code && modalMode === 'add' ? 'bg-success bg-opacity-10 border-success fw-bold text-success' : ''}
                  style={formData.code && modalMode === 'add' ? { fontSize: '1.1rem', fontWeight: 'bold', color: '#198754' } : {}}
                />
                {modalMode === 'add' && !formData.code && (
                  <small className="text-muted">Code will be auto-generated numerically</small>
                )}
                {formData.code && modalMode === 'add' && (
                  <small className="text-success fw-bold d-block mt-1">
                    ✓ Generated Code: <strong>{formData.code}</strong>
                  </small>
                )}
              </CCol>
            </CRow>

            <CRow className="mb-3">
              <CCol md={12}>
                <CFormLabel htmlFor="description">Description</CFormLabel>
                <CFormTextarea
                  id="description"
                  name="description"
                  value={formData.description}
                  onChange={handleChange}
                  rows={3}
                  placeholder="Enter item description"
                />
              </CCol>
            </CRow>

            <CRow className="mb-3">
              <CCol md={6} className="d-flex align-items-end">
                <CFormCheck
                  id="isActive"
                  name="isActive"
                  label="Active"
                  checked={formData.isActive}
                  onChange={handleChange}
                />
              </CCol>
            </CRow>
          </CForm>
        </CModalBody>
        <CModalFooter>
          <CButton color="secondary" onClick={() => setShowModal(false)}>
            Cancel
          </CButton>
          <CButton color="primary" onClick={handleSave} disabled={loading}>
            {loading ? (
              <>
                <CSpinner size="sm" className="me-2" />
                Saving...
              </>
            ) : (
              'Save Item'
            )}
          </CButton>
        </CModalFooter>
      </CModal>

      {/* Delete Confirmation Modal */}
      <CModal visible={showDeleteModal} onClose={handleCancelDelete}>
        <CModalHeader>
          <CModalTitle>
            <CIcon icon={cilTrash} className="me-2 text-danger" />
            Confirm Delete
          </CModalTitle>
        </CModalHeader>
        <CModalBody>
          <p className="mb-3">
            Are you sure you want to delete item <strong>{deleteItemName}</strong>?
          </p>
          <p className="text-danger mb-2">This will permanently delete:</p>
          <ul className="mb-3">
            <li>The item itself</li>
            <li>All rent rates associated with this item</li>
            <li>All discount rates associated with this item</li>
            <li>All advance rates associated with this item</li>
          </ul>
          <p className="text-danger fw-bold">This action cannot be undone!</p>
        </CModalBody>
        <CModalFooter>
          <CButton color="secondary" onClick={handleCancelDelete} disabled={loading}>
            Cancel
          </CButton>
          <CButton 
            color="danger" 
            onClick={handleDelete}
            disabled={loading}
          >
            {loading ? <CSpinner size="sm" /> : 'Delete'}
          </CButton>
        </CModalFooter>
      </CModal>
    </CRow>
  )
}

export default Items

